version: '3'
services:
  phpfpm:
    build: ./php/
    volumes:
      - ./app:/var/www/html
    restart: always
  nginx:
          #build: .
    build: ./nginx/
    volumes:
            #- ./app:/var/www/html
      - ./nginx/app:/usr/share/nginx/html
    restart: always
    ports:
      - "8085:80"
