from nginx:stable
COPY app /usr/share/nginx/html
#copy nginx.conf /etc/nginx/
copy default.conf /etc/nginx/conf.d/
run chown -R nginx:nginx /usr/share/nginx/html
STOPSIGNAL SIGTERM
CMD ["nginx", "-g", "daemon off;"] 
